# Generated by Django 5.0.2 on 2024-03-04 23:03

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_articles_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='content'),
        ),
    ]
