# Generated by Django 5.0.2 on 2024-03-03 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('carrier', models.CharField(choices=[('Software Enginneer', 'Software Enginneer'), ('Fullstack Enginneer', 'Fullstack Enginneer'), ('Frontend Developer', 'Frontend Developer'), ('Mobile App Developer', 'Mobile App Developer'), ('Backend Developer', 'Backend Developer'), ('Product Designer', 'Product Designer'), ('Product Manager', 'Product Manager'), ('System Analyst', 'System Analyst'), ('Digital Marketer', 'Digital Marketer'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Data Scientist', 'Data Scientist'), ('Network Enginneer', 'Network Enginneer'), ('Cybersecurity Specialist', 'Cybersecurity Specialist'), ('Security Engineer', 'Security Engineer'), ('Security Analyst', 'Security Analyst'), ('Database Administrator', 'Database Administrator'), ('Systems Administrator', 'Systems Administrator')], max_length=25)),
                ('photo', models.ImageField(blank=True, default='static/images/profile.jpg', null=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
