# Generated by Django 5.0.2 on 2024-03-05 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('source_code', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250)),
                ('live_demo', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('programmingLg', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Python', 'Python'), ('Java scripts', 'Java scripts'), ('Java', 'Java'), ('Kotlin', 'Kotlin'), ('C++', 'C++'), ('C#', 'C#'), ('Ruby', 'Ruby'), ('Swift', 'Swift'), ('Solidity', 'Solidity'), ('Dart', 'Dart')], max_length=25)),
                ('image', models.ImageField(upload_to='inspiration_images/')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='inspiration_publish_6c2d08_idx')],
            },
        ),
    ]
